use serde::{de::DeserializeOwned, Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Mutex, OnceLock};
use std::time::Duration;
use tauri::{Emitter, Manager};

#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

// How often the watcher samples the pasteboard. On macOS this only reads the
// cheap `changeCount`; the text is decoded only when the count actually moved.
const POLL_INTERVAL: Duration = Duration::from_millis(200);

// Copies larger than this are not logged to history. A multi-megabyte paste
// would otherwise be held in memory three times over (Rust state, JS array, DOM)
// and re-serialised on every subsequent copy. It stays on the system clipboard;
// ClipCork just doesn't record it.
const MAX_ENTRY_BYTES: usize = 100_000;

// Monotonic tail for entry ids so two copies in the same millisecond can't
// collide (row click handlers resolve by id).
static ID_COUNTER: AtomicU64 = AtomicU64::new(0);

fn next_id() -> String {
    format!(
        "{}-{}",
        now_millis(),
        ID_COUNTER.fetch_add(1, Ordering::Relaxed)
    )
}

// Gap between the bottom of the menu bar icon and the top of the panel.
const PANEL_GAP: f64 = 6.0;
// Keeps a panel anchored to an icon near the screen edge fully on-screen.
const SCREEN_MARGIN: f64 = 8.0;
// A click on the status item makes it key, so the panel blurs and hides just
// before the tray handler runs. Anything hidden this recently was closed by
// that same click and must not be reopened by it.
const REOPEN_GUARD_MS: u64 = 250;
// Opening over someone else's fullscreen space orders the panel in without
// activating this app, and AppKit can report a blur before key status settles.
// Auto-hiding on that blur makes the panel look like it never opened, so blurs
// this soon after a show are ignored.
const FOCUS_GUARD_MS: u64 = 250;

// macOS pasteboard privacy markers. Password managers (1Password, Keychain,
// Bitwarden, …) stamp copied secrets with ConcealedType precisely so clipboard
// managers skip them; Transient/AutoGenerated mark scratch and machine-produced
// content. Items carrying any of these are never recorded.
#[cfg(target_os = "macos")]
const PRIVATE_PASTEBOARD_TYPES: [&str; 3] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

#[derive(Serialize, Deserialize, Clone)]
struct Snippet {
    id: String,
    title: String,
    content: String,
    tag: String,
    created: u64,
    updated: u64,
    // Usage tracking for "most-used floats up" ordering (managed by the frontend;
    // declared here so Rust-side load/save round-trips don't drop them).
    #[serde(default)]
    uses: u64,
    #[serde(default)]
    last_used: u64,
}

#[derive(Serialize, Deserialize, Clone)]
struct ClipboardEntry {
    id: String,
    text: String,
    timestamp: u64,
    // Pinned entries survive the history cap and sort to the top.
    #[serde(default)]
    pinned: bool,
}

struct AppState {
    clipboard_history: Mutex<Vec<ClipboardEntry>>,
    // The watcher's dedupe key. Shared (not thread-local) so that
    // `clear_clipboard_history` can reset it — otherwise re-copying the text you
    // just cleared would be deduped away and never reappear.
    last_clipboard: Mutex<String>,
    history_limit: Mutex<usize>,
    recording_enabled: Mutex<bool>,
    // The exact text this app just wrote to the clipboard, so the watcher can
    // suppress recording its own write without dropping a genuine user copy that
    // happened to land in the same tick.
    skip_text: Mutex<Option<String>>,
    last_hidden_at: Mutex<u64>,
    // Timestamp of the most recent show, for FOCUS_GUARD_MS.
    last_shown_at: Mutex<u64>,
    // The tray icon's screen rect from its most recent event, so the panel can
    // be anchored under it even when opened from the right-click menu.
    last_tray_rect: Mutex<Option<tauri::Rect>>,
    // Custom snippets folder (for cloud-folder sync), synced from settings.
    snippets_dir: Mutex<Option<PathBuf>>,
}

// ---------------------------------------------------------------------------
// Persistence — pure, path-based, atomic, and permission-tight.
// ---------------------------------------------------------------------------

static DATA_DIR: OnceLock<PathBuf> = OnceLock::new();

// Resolved once and cached — this is on the clipboard-capture hot path, so it
// must not re-run `app_data_dir()` + two syscalls on every write.
fn ensure_data_dir(app: &tauri::AppHandle) -> PathBuf {
    DATA_DIR
        .get_or_init(|| {
            let dir = app
                .path()
                .app_data_dir()
                .unwrap_or_else(|_| std::env::temp_dir().join("clipcork"));
            let _ = fs::create_dir_all(&dir);
            #[cfg(unix)]
            {
                let _ = fs::set_permissions(&dir, fs::Permissions::from_mode(0o700));
            }
            dir
        })
        .clone()
}

fn app_file(app: &tauri::AppHandle, name: &str) -> PathBuf {
    ensure_data_dir(app).join(name)
}

fn data_path(app: &tauri::AppHandle) -> PathBuf {
    // Snippets may live in a user-chosen cloud folder; fall back to app-data.
    if let Some(state) = app.try_state::<AppState>() {
        if let Some(dir) = state.snippets_dir.lock().unwrap().clone() {
            let _ = fs::create_dir_all(&dir);
            return dir.join("snippets.json");
        }
    }
    app_file(app, "snippets.json")
}

fn history_path(app: &tauri::AppHandle) -> PathBuf {
    app_file(app, "clipboard_history.json")
}

fn settings_path(app: &tauri::AppHandle) -> PathBuf {
    app_file(app, "settings.json")
}

// Reads and parses `path`. A missing file yields the default. A file that
// exists but does not parse is moved aside to `*.corrupt.json` and the default
// returned — never silently treated as "empty" and then overwritten.
fn read_json<T: DeserializeOwned + Default>(path: &Path) -> T {
    let Ok(data) = fs::read_to_string(path) else {
        return T::default();
    };
    match serde_json::from_str(&data) {
        Ok(value) => value,
        Err(_) => {
            let _ = fs::rename(path, path.with_extension("corrupt.json"));
            T::default()
        }
    }
}

// Serializes to a temp file, tightens its mode to 0600, then atomically renames
// over the target. A crash or full disk can never leave a half-written file,
// and a serialize failure returns an error instead of clobbering good data.
fn write_json_atomic<T: Serialize>(path: &Path, value: &T) -> std::io::Result<()> {
    let json = serde_json::to_string_pretty(value)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
    let tmp = path.with_extension("json.tmp");
    fs::write(&tmp, json.as_bytes())?;
    #[cfg(unix)]
    {
        fs::set_permissions(&tmp, fs::Permissions::from_mode(0o600))?;
    }
    fs::rename(&tmp, path)
}

fn now_millis() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------

#[derive(Serialize, Deserialize, Clone)]
struct Settings {
    #[serde(default = "default_limit")]
    history_limit: usize,
    // Whether clipboard recording is active. `#[serde(default)]` so upgrading an
    // existing settings.json (which predates this field) keeps recording on
    // rather than silently resetting every field to Default.
    #[serde(default = "default_enabled")]
    enabled: bool,
    // Optional folder (e.g. inside iCloud Drive / Dropbox) to store snippets.json
    // in, so a personal snippet library syncs across Macs. History and settings
    // always stay in the local app-data dir.
    #[serde(default)]
    snippets_dir: Option<String>,
}

fn default_limit() -> usize {
    20
}

fn default_enabled() -> bool {
    true
}

impl Default for Settings {
    fn default() -> Self {
        Self {
            history_limit: default_limit(),
            enabled: default_enabled(),
            snippets_dir: None,
        }
    }
}

fn load_settings(app: &tauri::AppHandle) -> Settings {
    let path = settings_path(app);
    if path.exists() {
        read_json(&path)
    } else {
        let s = Settings::default();
        let _ = write_json_atomic(&path, &s);
        s
    }
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

#[tauri::command]
fn load_snippets(app: tauri::AppHandle) -> Vec<Snippet> {
    read_json(&data_path(&app))
}

#[tauri::command]
fn save_snippets(app: tauri::AppHandle, snippets: Vec<Snippet>) {
    let _ = write_json_atomic(&data_path(&app), &snippets);
}

#[tauri::command]
fn get_data_path(app: tauri::AppHandle) -> String {
    // The containing folder, not just snippets.json, so the UI can honestly show
    // where the clipboard log lives too.
    ensure_data_dir(&app).to_string_lossy().to_string()
}

#[tauri::command]
fn write_clipboard(state: tauri::State<'_, AppState>, text: String) -> bool {
    // An explicit user Copy: put it on the pasteboard normally (do not exclude
    // it from other clipboard managers — the user asked for this value to be
    // available), and mark it so our own watcher doesn't re-record it.
    if set_clipboard_plain(&text) {
        *state.skip_text.lock().unwrap() = Some(text);
        true
    } else {
        false
    }
}

#[tauri::command]
fn load_clipboard_history(app: tauri::AppHandle) -> Vec<ClipboardEntry> {
    read_json(&history_path(&app))
}

#[tauri::command]
fn get_settings(app: tauri::AppHandle) -> Settings {
    let settings = load_settings(&app);
    // Keep AppState in sync with disk so the watcher and the UI can't drift.
    if let Some(state) = app.try_state::<AppState>() {
        *state.history_limit.lock().unwrap() = settings.history_limit;
        *state.recording_enabled.lock().unwrap() = settings.enabled;
    }
    settings
}

#[tauri::command]
fn save_settings_cmd(app: tauri::AppHandle, settings: Settings) {
    let _ = write_json_atomic(&settings_path(&app), &settings);
    if let Some(state) = app.try_state::<AppState>() {
        *state.history_limit.lock().unwrap() = settings.history_limit;
        *state.recording_enabled.lock().unwrap() = settings.enabled;
        *state.snippets_dir.lock().unwrap() =
            settings.snippets_dir.as_ref().map(PathBuf::from);
    }
}

#[tauri::command]
fn toggle_pin(state: tauri::State<'_, AppState>, app: tauri::AppHandle, id: String) -> bool {
    let (snapshot, pinned) = {
        let mut history = state.clipboard_history.lock().unwrap();
        let mut pinned = false;
        if let Some(e) = history.iter_mut().find(|e| e.id == id) {
            e.pinned = !e.pinned;
            pinned = e.pinned;
        }
        (history.clone(), pinned)
    };
    let _ = write_json_atomic(&history_path(&app), &snapshot);
    pinned
}

#[tauri::command]
fn clear_clipboard_history(state: tauri::State<'_, AppState>, app: tauri::AppHandle) {
    state.clipboard_history.lock().unwrap().clear();
    // Reset the dedupe key so re-copying the just-cleared text records again.
    *state.last_clipboard.lock().unwrap() = String::new();
    let _ = write_json_atomic(&history_path(&app), &Vec::<ClipboardEntry>::new());
}

#[tauri::command]
fn pin_to_snippets(app: tauri::AppHandle, content: String) -> Snippet {
    let mut snippets = load_snippets(app.clone());

    let now = now_millis();
    let preview: String = content.chars().take(50).collect();
    let title = if preview.chars().count() < content.chars().count() {
        preview + "..."
    } else {
        preview
    };
    let snippet = Snippet {
        id: next_id(),
        title,
        content,
        tag: String::new(),
        created: now,
        updated: now,
        uses: 0,
        last_used: 0,
    };

    snippets.insert(0, snippet.clone());
    save_snippets(app, snippets);
    snippet
}

#[tauri::command]
fn open_url(url: String) {
    // Only http(s) — never hand an arbitrary scheme or file path from clipboard
    // content to `open`.
    if url.starts_with("http://") || url.starts_with("https://") {
        let _ = std::process::Command::new("open").arg(&url).spawn();
    }
}

#[tauri::command]
fn reveal_path(path: String) {
    let _ = std::process::Command::new("open").arg("-R").arg(&path).spawn();
}

// Point the snippet store at a folder (e.g. iCloud Drive) or back to local
// (None). Returns the effective snippet list: an existing file in the target
// wins (adopting already-synced snippets); otherwise the current set seeds it.
#[tauri::command]
fn set_snippets_dir(
    app: tauri::AppHandle,
    state: tauri::State<'_, AppState>,
    dir: Option<String>,
) -> Vec<Snippet> {
    let current = load_snippets(app.clone());
    let mut settings = load_settings(&app);
    settings.snippets_dir = dir.clone();
    let _ = write_json_atomic(&settings_path(&app), &settings);
    *state.snippets_dir.lock().unwrap() = dir.as_ref().map(PathBuf::from);

    let new_path = data_path(&app);
    if new_path.exists() {
        read_json(&new_path)
    } else {
        let _ = write_json_atomic(&new_path, &current);
        current
    }
}

#[tauri::command]
fn get_snippets_dir(app: tauri::AppHandle) -> Option<String> {
    load_settings(&app).snippets_dir
}

#[tauri::command]
fn export_snippets_to(app: tauri::AppHandle, path: String) -> bool {
    let snippets = load_snippets(app.clone());
    match serde_json::to_string_pretty(&snippets) {
        Ok(json) => fs::write(&path, json).is_ok(),
        Err(_) => false,
    }
}

#[tauri::command]
fn import_snippets_from(path: String) -> Vec<Snippet> {
    match fs::read_to_string(&path) {
        Ok(data) => serde_json::from_str(&data).unwrap_or_default(),
        Err(_) => Vec::new(),
    }
}

// Open-at-login. The launch agent the plugin writes is the source of truth —
// deliberately not mirrored into settings.json, which would only give the two
// a chance to disagree after the user removes the item in System Settings.
#[tauri::command]
fn get_autostart(app: tauri::AppHandle) -> bool {
    use tauri_plugin_autostart::ManagerExt;
    app.autolaunch().is_enabled().unwrap_or(false)
}

// Returns the state that actually took effect, so a failed write shows up in
// the UI as the switch springing back rather than a lie that sticks.
#[tauri::command]
fn set_autostart(app: tauri::AppHandle, enabled: bool) -> bool {
    use tauri_plugin_autostart::ManagerExt;
    let manager = app.autolaunch();
    let _ = if enabled {
        manager.enable()
    } else {
        manager.disable()
    };
    manager.is_enabled().unwrap_or(false)
}

#[tauri::command(async)]
fn paste_and_hide(app: tauri::AppHandle, state: tauri::State<'_, AppState>, text: String) -> bool {
    // Without Accessibility permission CGEvent posting silently no-ops. Report
    // that honestly so the UI can prompt, instead of claiming success.
    #[cfg(target_os = "macos")]
    if !accessibility_trusted() {
        return false;
    }

    // Transient transport for the synthetic paste — mark it so other clipboard
    // managers on the machine don't also capture the secret.
    if !set_clipboard_excluded(&text) {
        return false;
    }
    *state.skip_text.lock().unwrap() = Some(text);

    if let Some(window) = app.get_webview_window("main") {
        hide_panel(&window);
    }

    // Give macOS time to restore focus to the previously-frontmost app before
    // the keystroke lands. Runs on an async command worker, so it does not block
    // the main/UI thread.
    std::thread::sleep(Duration::from_millis(350));

    simulate_paste()
}

// ---------------------------------------------------------------------------
// Clipboard I/O helpers
// ---------------------------------------------------------------------------

fn set_clipboard_plain(text: &str) -> bool {
    match arboard::Clipboard::new() {
        Ok(mut cb) => cb.set_text(text).is_ok(),
        Err(_) => false,
    }
}

#[cfg(target_os = "macos")]
fn set_clipboard_excluded(text: &str) -> bool {
    use arboard::SetExtApple;
    match arboard::Clipboard::new() {
        Ok(mut cb) => cb.set().exclude_from_history().text(text).is_ok(),
        Err(_) => false,
    }
}

#[cfg(not(target_os = "macos"))]
fn set_clipboard_excluded(text: &str) -> bool {
    set_clipboard_plain(text)
}

fn current_clipboard_text() -> String {
    match arboard::Clipboard::new() {
        Ok(mut cb) => cb.get_text().unwrap_or_default(),
        Err(_) => String::new(),
    }
}

#[cfg(target_os = "macos")]
fn accessibility_trusted() -> bool {
    // Declared locally; AXIsProcessTrusted lives in the ApplicationServices
    // framework, linked via build.rs / the objc2 frameworks already in the tree.
    #[link(name = "ApplicationServices", kind = "framework")]
    extern "C" {
        fn AXIsProcessTrusted() -> u8;
    }
    unsafe { AXIsProcessTrusted() != 0 }
}

// Posts ⌘V. All four events are constructed before any is posted, so a
// construction failure can never leave the Command modifier latched.
#[cfg(target_os = "macos")]
fn simulate_paste() -> bool {
    use core_graphics::event::{CGEvent, CGEventFlags, CGEventTapLocation, CGKeyCode};
    use core_graphics::event_source::CGEventSource;
    use core_graphics::event_source::CGEventSourceStateID::HIDSystemState;

    let Ok(source) = CGEventSource::new(HIDSystemState) else {
        return false;
    };

    let cmd: CGKeyCode = 55;
    let v: CGKeyCode = 9;

    let (Ok(cmd_down), Ok(v_down), Ok(v_up), Ok(cmd_up)) = (
        CGEvent::new_keyboard_event(source.clone(), cmd, true),
        CGEvent::new_keyboard_event(source.clone(), v, true),
        CGEvent::new_keyboard_event(source.clone(), v, false),
        CGEvent::new_keyboard_event(source.clone(), cmd, false),
    ) else {
        return false;
    };

    cmd_down.set_flags(CGEventFlags::CGEventFlagCommand);
    cmd_down.post(CGEventTapLocation::HID);
    v_down.set_flags(CGEventFlags::CGEventFlagCommand);
    v_down.post(CGEventTapLocation::HID);
    v_up.set_flags(CGEventFlags::CGEventFlagCommand);
    v_up.post(CGEventTapLocation::HID);
    cmd_up.post(CGEventTapLocation::HID);
    true
}

#[cfg(not(target_os = "macos"))]
fn simulate_paste() -> bool {
    false
}

// ---------------------------------------------------------------------------
// Clipboard watcher
// ---------------------------------------------------------------------------

struct Sample {
    text: String,
    is_private: bool,
}

#[cfg(target_os = "macos")]
fn current_change_count() -> isize {
    use objc2_app_kit::NSPasteboard;
    objc2::rc::autoreleasepool(|_| NSPasteboard::generalPasteboard().changeCount())
}

#[cfg(target_os = "macos")]
fn pasteboard_is_private(pb: &objc2_app_kit::NSPasteboard) -> bool {
    let Some(types) = pb.types() else {
        return false;
    };
    let count = types.count();
    for i in 0..count {
        let t = types.objectAtIndex(i);
        let s = t.to_string();
        if PRIVATE_PASTEBOARD_TYPES.iter().any(|m| *m == s) {
            return true;
        }
    }
    false
}

// Returns a fresh clipboard sample only when the pasteboard actually changed.
#[cfg(target_os = "macos")]
fn poll_clipboard(last_change: &mut isize) -> Option<Sample> {
    use objc2_app_kit::NSPasteboard;
    let (changed, is_private) = objc2::rc::autoreleasepool(|_| {
        let pb = NSPasteboard::generalPasteboard();
        let cc = pb.changeCount();
        if cc == *last_change {
            return (false, false);
        }
        *last_change = cc;
        (true, pasteboard_is_private(&pb))
    });
    if !changed {
        return None;
    }
    let text = current_clipboard_text();
    if text.is_empty() {
        return None;
    }
    Some(Sample { text, is_private })
}

#[cfg(not(target_os = "macos"))]
fn poll_clipboard(_last_change: &mut isize) -> Option<Sample> {
    let text = current_clipboard_text();
    if text.is_empty() {
        return None;
    }
    Some(Sample {
        text,
        is_private: false,
    })
}

fn push_capped(history: &mut Vec<ClipboardEntry>, entry: ClipboardEntry, limit: usize) {
    history.insert(0, entry);
    // Evict the oldest UNPINNED entries beyond the limit; pinned entries always
    // stay, so the cap governs the unpinned tail only.
    let mut unpinned = history.iter().filter(|e| !e.pinned).count();
    let mut i = history.len();
    while unpinned > limit && i > 0 {
        i -= 1;
        if !history[i].pinned {
            history.remove(i);
            unpinned -= 1;
        }
    }
}

fn process_sample(app: &tauri::AppHandle, sample: Sample) {
    let state = app.state::<AppState>();

    let enabled = *state.recording_enabled.lock().unwrap();
    // Recording off, or a privacy-marked item (a copied password): absorb it
    // into the dedupe key so it is neither recorded now nor re-evaluated later,
    // but never persisted.
    if !enabled || sample.is_private {
        *state.last_clipboard.lock().unwrap() = sample.text;
        return;
    }

    // Our own write (Copy / paste): suppress exactly that text, once.
    let pending = state.skip_text.lock().unwrap().take();
    if let Some(p) = pending {
        if p == sample.text {
            *state.last_clipboard.lock().unwrap() = sample.text;
            return;
        }
    }

    {
        let mut last = state.last_clipboard.lock().unwrap();
        if *last == sample.text {
            return;
        }
        *last = sample.text.clone();
    }

    // Don't log oversized pastes — it's still on the clipboard, just not recorded.
    if sample.text.len() > MAX_ENTRY_BYTES {
        return;
    }

    let now = now_millis();
    let text = sample.text;
    let limit = *state.history_limit.lock().unwrap();

    // Mutate under the lock, clone, then write/emit outside it — the disk write
    // never blocks a main-thread command waiting on this mutex.
    let (snapshot, entry) = {
        let mut history = state.clipboard_history.lock().unwrap();
        // Move-to-top: if this exact text is already in history, drop the old
        // copy (carrying its pinned flag forward) rather than duplicating it.
        let was_pinned = history
            .iter()
            .find(|e| e.text == text)
            .map(|e| e.pinned)
            .unwrap_or(false);
        history.retain(|e| e.text != text);
        let entry = ClipboardEntry {
            id: next_id(),
            text,
            timestamp: now,
            pinned: was_pinned,
        };
        push_capped(&mut history, entry.clone(), limit);
        (history.clone(), entry)
    };

    let _ = write_json_atomic(&history_path(app), &snapshot);
    let _ = app.emit("clipboard-update", &entry);
}

fn start_clipboard_watcher(app: tauri::AppHandle) {
    std::thread::spawn(move || {
        // Seed the dedupe key with whatever is already on the clipboard so the
        // pre-existing clipboard isn't recorded as a fresh copy on the first tick.
        let seed = current_clipboard_text();
        *app.state::<AppState>().last_clipboard.lock().unwrap() = seed;

        let mut last_change: isize = {
            #[cfg(target_os = "macos")]
            {
                current_change_count()
            }
            #[cfg(not(target_os = "macos"))]
            {
                0
            }
        };

        loop {
            std::thread::sleep(POLL_INTERVAL);
            if let Some(sample) = poll_clipboard(&mut last_change) {
                process_sample(&app, sample);
            }
        }
    });
}

// ---------------------------------------------------------------------------
// One-time migration from the pre-Beecork identifier
// ---------------------------------------------------------------------------

// The app shipped earlier under bundle id `com.clipvault`, so its data lived in
// `…/Application Support/com.clipvault/`. Renaming to `com.beecork.clipcork`
// moves the data directory; copy the old files across once so existing snippets
// and history survive the rename.
fn migrate_legacy_data(app: &tauri::AppHandle) {
    let new_dir = ensure_data_dir(app);
    if new_dir.join("snippets.json").exists() || new_dir.join("clipboard_history.json").exists() {
        return;
    }
    let Some(parent) = new_dir.parent() else {
        return;
    };
    let old_dir = parent.join("com.clipvault");
    if !old_dir.exists() {
        return;
    }
    for name in ["snippets.json", "clipboard_history.json", "settings.json"] {
        let src = old_dir.join(name);
        let dst = new_dir.join(name);
        if src.exists() && !dst.exists() && fs::copy(&src, &dst).is_ok() {
            // fs::copy preserves the source's (looser) mode; tighten to owner-only.
            #[cfg(unix)]
            {
                let _ = fs::set_permissions(&dst, fs::Permissions::from_mode(0o600));
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Menu-bar panel (NSPanel) plumbing
// ---------------------------------------------------------------------------

// macOS treats a borderless window in an Accessory app as an ordinary window:
// it belongs to a single space, refuses key status, and is painted underneath
// any fullscreen app. Reclassifying it as a nonactivating NSPanel is what makes
// it behave like a real menu bar extra — able to float above someone else's
// fullscreen space, and to take keyboard focus without activating this app
// (activating is what yanks the user out of their fullscreen space).
#[cfg(target_os = "macos")]
mod panel {
    use objc2::runtime::AnyObject;
    use objc2::{define_class, ClassType, MainThreadOnly};
    use objc2_app_kit::{
        NSColor, NSPanel, NSPopUpMenuWindowLevel, NSWindow, NSWindowCollectionBehavior,
        NSWindowStyleMask,
    };

    define_class!(
        // SAFETY:
        // - NSPanel's only subclassing requirement is that it stays main-thread.
        // - ClipCorkPanel declares no ivars and no Drop, which is what makes it
        //   safe to graft onto a window instance AppKit has already allocated:
        //   the isa-swap cannot enlarge the allocation, so there is no OOB write.
        // - Grafting discards tao's own NSWindow subclass overrides and the
        //   original class's `dealloc` never runs; both are acceptable here.
        // - All call sites are on the main thread (setup / tray-click handler),
        //   which the raw-pointer `&NSWindow` reconstructions below rely on.
        #[unsafe(super(NSPanel))]
        #[thread_kind = MainThreadOnly]
        #[name = "ClipCorkPanel"]
        struct ClipCorkPanel;

        impl ClipCorkPanel {
            // Borderless windows answer NO here, which would leave the search
            // field unable to receive a single keystroke.
            #[unsafe(method(canBecomeKeyWindow))]
            fn can_become_key_window(&self) -> bool {
                true
            }
        }
    );

    // What actually lets the panel draw over someone else's fullscreen space:
    // a level above the menu bar, plus membership in every space rather than
    // the one it was born in. Neither is sticky — a window that has never been
    // ordered in, or that was ordered out while a fullscreen space was being
    // torn down and rebuilt, can come back bound to a single space and end up
    // behind the fullscreen app. Cheap enough to re-assert before every show.
    fn apply_float_behavior(ns_window: &NSWindow) {
        // Above the menu bar (24) and the Dock (20), which is where real menu
        // bar popovers live. A merely "floating" window (3) loses to fullscreen.
        ns_window.setLevel(NSPopUpMenuWindowLevel);
        ns_window.setCollectionBehavior(
            NSWindowCollectionBehavior::CanJoinAllSpaces
                | NSWindowCollectionBehavior::FullScreenAuxiliary
                | NSWindowCollectionBehavior::Stationary,
        );
    }

    pub fn adopt(window: &tauri::WebviewWindow) {
        let Ok(ptr) = window.ns_window() else {
            return;
        };

        unsafe {
            objc2::ffi::object_setClass(ptr as *mut AnyObject, ClipCorkPanel::class());
        }

        let ns_window: &NSWindow = unsafe { &*(ptr as *const NSWindow) };
        ns_window
            .setStyleMask(NSWindowStyleMask::Borderless | NSWindowStyleMask::NonactivatingPanel);
        apply_float_behavior(ns_window);
        // NSPanel — unlike NSWindow — defaults hidesOnDeactivate to YES, so
        // AppKit would order the panel out whenever this app is not the active
        // one. For a menu bar extra opened over another app's fullscreen space,
        // this app is never the active one.
        ns_window.setHidesOnDeactivate(false);
        // Make the window itself clear so the NSVisualEffectView (applied after
        // adopt) is what the user sees — a transparent window with an opaque
        // background color would hide the vibrancy entirely.
        ns_window.setOpaque(false);
        let clear = NSColor::clearColor();
        ns_window.setBackgroundColor(Some(&clear));
    }

    // Re-assert the float attributes while the window is still hidden, so the
    // show that follows lands in whatever space the user is in right now.
    pub fn prepare(window: &tauri::WebviewWindow) {
        let Ok(ptr) = window.ns_window() else {
            return;
        };
        let ns_window: &NSWindow = unsafe { &*(ptr as *const NSWindow) };
        apply_float_behavior(ns_window);
    }

    pub fn make_key(window: &tauri::WebviewWindow) {
        let Ok(ptr) = window.ns_window() else {
            return;
        };
        let ns_window: &NSWindow = unsafe { &*(ptr as *const NSWindow) };
        // Deliberately not tauri's set_focus(), which calls
        // activateIgnoringOtherApps and switches spaces out from under the user.
        ns_window.makeKeyAndOrderFront(None);
        // makeKeyAndOrderFront: only orders reliably for the *active* app, and
        // a menu bar extra never is one. Without this the panel intermittently
        // opens behind the window the user is looking at.
        ns_window.orderFrontRegardless();
    }
}

// Anchors the panel under the menu bar icon that was clicked, rather than
// letting it open wherever the window happened to be last.
fn position_under_tray(window: &tauri::WebviewWindow, rect: tauri::Rect) {
    let Ok(size) = window.outer_size() else {
        return;
    };

    // The tray reports its rect in whatever unit it pleases; the window is
    // positioned in physical pixels, so normalise before doing any arithmetic.
    let scale = window.scale_factor().unwrap_or(1.0);
    let icon_pos = rect.position.to_physical::<f64>(scale);
    let icon_size = rect.size.to_physical::<f64>(scale);

    let icon_center_x = icon_pos.x + icon_size.width / 2.0;
    let mut x = icon_center_x - size.width as f64 / 2.0;
    let y = icon_pos.y + icon_size.height + PANEL_GAP;

    // An icon near the right edge would otherwise push half the panel off the
    // side of the display it belongs to.
    if let Ok(Some(monitor)) = window
        .app_handle()
        .monitor_from_point(icon_center_x, icon_pos.y)
    {
        let left = monitor.position().x as f64 + SCREEN_MARGIN;
        let right = monitor.position().x as f64 + monitor.size().width as f64
            - size.width as f64
            - SCREEN_MARGIN;
        if right >= left {
            x = x.clamp(left, right);
        }
    }

    let _ = window.set_position(tauri::PhysicalPosition::new(x, y));
}

fn show_panel(window: &tauri::WebviewWindow) {
    #[cfg(target_os = "macos")]
    panel::prepare(window);

    let _ = window.show();

    #[cfg(target_os = "macos")]
    panel::make_key(window);

    #[cfg(not(target_os = "macos"))]
    let _ = window.set_focus();

    if let Some(state) = window.app_handle().try_state::<AppState>() {
        *state.last_shown_at.lock().unwrap() = now_millis();
    }

    // Let the frontend reset its search query, selection and scroll on each open.
    let _ = window.emit("panel-shown", ());
}

// Global-hotkey entry point. Deliberately not `toggle_panel` — that path's
// REOPEN_GUARD_MS exists to absorb the status item's own click and would eat
// rapid hotkey presses.
fn toggle_from_hotkey(app: &tauri::AppHandle) {
    let Some(window) = app.get_webview_window("main") else {
        return;
    };
    if window.is_visible().unwrap_or(false) {
        hide_panel(&window);
        return;
    }
    if let Some(rect) = app.state::<AppState>().last_tray_rect.lock().unwrap().clone() {
        position_under_tray(&window, rect);
    }
    show_panel(&window);
}

fn hide_panel(window: &tauri::WebviewWindow) {
    let _ = window.hide();
    let state = window.app_handle().state::<AppState>();
    *state.last_hidden_at.lock().unwrap() = now_millis();
}

fn toggle_panel(window: &tauri::WebviewWindow, rect: tauri::Rect) {
    if window.is_visible().unwrap_or(false) {
        hide_panel(window);
        return;
    }

    let hidden_ago = {
        let state = window.app_handle().state::<AppState>();
        let last = *state.last_hidden_at.lock().unwrap();
        now_millis().saturating_sub(last)
    };
    if hidden_ago < REOPEN_GUARD_MS {
        return;
    }

    position_under_tray(window, rect);
    show_panel(window);
}

// Opens the panel to the Settings tab from the tray menu, anchored under the
// icon if we've seen its position.
fn open_settings(app: &tauri::AppHandle) {
    if let Some(window) = app.get_webview_window("main") {
        if let Some(rect) = app.state::<AppState>().last_tray_rect.lock().unwrap().clone() {
            position_under_tray(&window, rect);
        }
        show_panel(&window);
        let _ = app.emit("open-settings", ());
    }
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_dialog::init())
        // LaunchAgent rather than the AppleScript launcher: it needs no
        // Automation permission prompt and works back to macOS 11.
        .plugin(tauri_plugin_autostart::init(
            tauri_plugin_autostart::MacosLauncher::LaunchAgent,
            None,
        ))
        .plugin(
            tauri_plugin_global_shortcut::Builder::new()
                .with_shortcut("Cmd+Shift+V")
                .expect("valid global shortcut")
                .with_handler(|app, _shortcut, event| {
                    if event.state == tauri_plugin_global_shortcut::ShortcutState::Pressed {
                        toggle_from_hotkey(app);
                    }
                })
                .build(),
        )
        .manage(AppState {
            clipboard_history: Mutex::new(Vec::new()),
            last_clipboard: Mutex::new(String::new()),
            history_limit: Mutex::new(default_limit()),
            recording_enabled: Mutex::new(default_enabled()),
            skip_text: Mutex::new(None),
            last_hidden_at: Mutex::new(0),
            last_shown_at: Mutex::new(0),
            last_tray_rect: Mutex::new(None),
            snippets_dir: Mutex::new(None),
        })
        .on_window_event(|window, event| {
            // Clicking away should dismiss the panel, the way every other menu
            // bar extra behaves.
            if let tauri::WindowEvent::Focused(false) = event {
                // …except for the blur that can arrive in the same instant as
                // the show, before key status settles over a fullscreen space.
                // Acting on that one would dismiss the panel the user just
                // opened; Esc and the tray icon still close it either way.
                if let Some(state) = window.app_handle().try_state::<AppState>() {
                    let shown_ago =
                        now_millis().saturating_sub(*state.last_shown_at.lock().unwrap());
                    if shown_ago < FOCUS_GUARD_MS {
                        return;
                    }
                }
                if let Some(panel) = window.get_webview_window("main") {
                    hide_panel(&panel);
                }
            }
        })
        .setup(|app| {
            let app_handle = app.handle().clone();

            // Migrate old data, then hydrate in-memory state from disk *before*
            // the watcher starts — otherwise its first write overwrites the
            // persisted history with a single entry.
            migrate_legacy_data(&app_handle);
            let settings = load_settings(&app_handle);
            {
                let state = app_handle.state::<AppState>();
                *state.history_limit.lock().unwrap() = settings.history_limit;
                *state.recording_enabled.lock().unwrap() = settings.enabled;
                *state.snippets_dir.lock().unwrap() =
                    settings.snippets_dir.as_ref().map(PathBuf::from);
                *state.clipboard_history.lock().unwrap() =
                    load_clipboard_history(app_handle.clone());
            }

            #[cfg(target_os = "macos")]
            {
                use objc2::MainThreadMarker;
                use objc2_app_kit::{NSApplication, NSApplicationActivationPolicy};
                use tauri::menu::{Menu, MenuItem, PredefinedMenuItem};
                use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};

                let mtm = MainThreadMarker::new().expect("not on main thread");
                let ns_app = NSApplication::sharedApplication(mtm);
                ns_app.setActivationPolicy(NSApplicationActivationPolicy::Accessory);

                let icon = tauri::image::Image::from_bytes(include_bytes!("../icons/tray.png"))
                    .expect("failed to load tray icon");

                // Right-click menu: the only way to reach Settings without the
                // panel, and the only way to quit (an Accessory app has no Dock
                // icon or app menu).
                let settings_item =
                    MenuItem::with_id(&app_handle, "settings", "Settings", true, None::<&str>)?;
                let quit_item = MenuItem::with_id(
                    &app_handle,
                    "quit",
                    "Quit ClipCork",
                    true,
                    Some("Cmd+Q"),
                )?;
                let sep = PredefinedMenuItem::separator(&app_handle)?;
                let menu = Menu::with_items(&app_handle, &[&settings_item, &sep, &quit_item])?;

                let _tray = TrayIconBuilder::new()
                    .icon(icon)
                    .tooltip("ClipCork")
                    .menu(&menu)
                    // Left-click toggles the panel; the menu is right-click only.
                    .show_menu_on_left_click(false)
                    .on_menu_event(|app, event| match event.id.as_ref() {
                        "quit" => app.exit(0),
                        "settings" => open_settings(app),
                        _ => {}
                    })
                    .on_tray_icon_event(move |tray, event| {
                        // Remember the icon's position for menu-triggered opens
                        // (hovering to right-click keeps this fresh).
                        let rect = match &event {
                            TrayIconEvent::Click { rect, .. }
                            | TrayIconEvent::DoubleClick { rect, .. }
                            | TrayIconEvent::Enter { rect, .. }
                            | TrayIconEvent::Move { rect, .. }
                            | TrayIconEvent::Leave { rect, .. } => Some(rect.clone()),
                            _ => None,
                        };
                        if let Some(rect) = rect {
                            if let Some(state) = tray.app_handle().try_state::<AppState>() {
                                *state.last_tray_rect.lock().unwrap() = Some(rect);
                            }
                        }
                        if let TrayIconEvent::Click {
                            button: MouseButton::Left,
                            button_state: MouseButtonState::Up,
                            rect,
                            ..
                        } = event
                        {
                            let app = tray.app_handle();
                            if let Some(window) = app.get_webview_window("main") {
                                toggle_panel(&window, rect);
                            }
                        }
                    })
                    .build(&app_handle)
                    .expect("failed to build tray");
            }

            if let Some(window) = app.get_webview_window("main") {
                #[cfg(target_os = "macos")]
                {
                    panel::adopt(&window);
                    // Real macOS glass: the Popover material is exactly what
                    // AppKit uses for menu-bar popovers, and it follows system
                    // appearance. `Active` state keeps it from desaturating during
                    // the focus handoff in `paste_and_hide`.
                    use window_vibrancy::{
                        apply_vibrancy, NSVisualEffectMaterial, NSVisualEffectState,
                    };
                    let _ = apply_vibrancy(
                        &window,
                        NSVisualEffectMaterial::Popover,
                        Some(NSVisualEffectState::Active),
                        Some(12.0),
                    );
                }
                let _ = window.hide();
            }

            start_clipboard_watcher(app_handle);

            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            load_snippets,
            save_snippets,
            get_data_path,
            write_clipboard,
            load_clipboard_history,
            get_settings,
            save_settings_cmd,
            clear_clipboard_history,
            toggle_pin,
            pin_to_snippets,
            open_url,
            reveal_path,
            set_snippets_dir,
            get_snippets_dir,
            export_snippets_to,
            import_snippets_from,
            get_autostart,
            set_autostart,
            paste_and_hide,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

// ---------------------------------------------------------------------------
// Tests — the persistence layer that owns the user's only copy of their data.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch_dir(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("clipcork_test_{}_{}", std::process::id(), tag));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn entry(id: &str) -> ClipboardEntry {
        ClipboardEntry {
            id: id.to_string(),
            text: format!("text-{id}"),
            timestamp: 1,
            pinned: false,
        }
    }

    #[test]
    fn write_then_read_roundtrips() {
        let dir = scratch_dir("roundtrip");
        let path = dir.join("clipboard_history.json");
        let data = vec![entry("a"), entry("b")];
        write_json_atomic(&path, &data).unwrap();
        let back: Vec<ClipboardEntry> = read_json(&path);
        assert_eq!(back.len(), 2);
        assert_eq!(back[0].id, "a");
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn missing_file_yields_default_without_side_effects() {
        let dir = scratch_dir("missing");
        let path = dir.join("nope.json");
        let back: Vec<ClipboardEntry> = read_json(&path);
        assert!(back.is_empty());
        assert!(!path.with_extension("corrupt.json").exists());
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn corrupt_file_is_moved_aside_not_treated_as_empty() {
        let dir = scratch_dir("corrupt");
        let path = dir.join("snippets.json");
        fs::write(&path, b"{ this is not valid json").unwrap();
        let back: Vec<Snippet> = read_json(&path);
        assert!(back.is_empty());
        // Original is preserved under *.corrupt.json rather than silently lost.
        assert!(!path.exists());
        assert!(path.with_extension("corrupt.json").exists());
        let _ = fs::remove_dir_all(&dir);
    }

    #[cfg(unix)]
    #[test]
    fn writes_are_owner_only() {
        let dir = scratch_dir("perms");
        let path = dir.join("settings.json");
        write_json_atomic(&path, &Settings::default()).unwrap();
        let mode = fs::metadata(&path).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o600);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn push_capped_keeps_newest_and_enforces_limit() {
        let mut history = Vec::new();
        for i in 0..5 {
            push_capped(&mut history, entry(&i.to_string()), 3);
        }
        assert_eq!(history.len(), 3);
        // Newest first, oldest dropped.
        assert_eq!(history[0].id, "4");
        assert_eq!(history[2].id, "2");
    }

    #[test]
    fn pinned_entries_survive_the_cap() {
        let mut history: Vec<ClipboardEntry> = Vec::new();
        let mut pin = entry("pinned");
        pin.pinned = true;
        history.push(pin);
        // Push 3 unpinned with a limit of 2 — one unpinned should be evicted,
        // the pinned one must remain.
        for i in 0..3 {
            push_capped(&mut history, entry(&i.to_string()), 2);
        }
        assert!(history.iter().any(|e| e.id == "pinned"));
        assert_eq!(history.iter().filter(|e| !e.pinned).count(), 2);
    }

    #[test]
    fn settings_default_enables_recording() {
        let s = Settings::default();
        assert!(s.enabled);
        assert_eq!(s.history_limit, 20);
    }
}
